# -*- coding: utf-8 -*-
"""Copy of Dumpsites_emission_FOD_estimation_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dbVgxN4am00_59K7PV-3uHnLwWDYrTdC
"""

import numpy as np
import pandas as pd
from openpyxl import load_workbook
from google.colab import files  # Import the files module

# Upload the Excel file using Colab's file upload feature
uploaded = files.upload()

# Assuming you've uploaded a file named "inputs.xlsx"
input_data = pd.read_excel(next(iter(uploaded)))


# Constants
MCF = 0.80   # Methane correction factor (MCF).
DOCf = 0.50  # Fraction of degradable organic carbon dissimilated (DOCF).
M = 13.00 #Process start in deposition year.
F = 0.50 # F= fraction of methane in landfill gas (LFG).

# Initialize arrays or lists
H = [0] * 101
E = [0] * 101
B = [0] * 101
C = [0] * 101
Q = [0] * 101

# Iterate through each row of input data
for index, row in input_data.iterrows():
    W = row["W"]  #  Amount of waste disposed (Gg/year)
    DOC = row["DOC"]  # DOC= = degradable organic carbon in the year of deposition, fraction.
    k = row["k"]  # Methane generation rate constant (k) (years-1)

 # Calculate exp2 and exp1 based on the value of k for this row
    exp2 = np.exp(-k * ((13.0 - M) / 12.0))
    exp1 = np.exp(-k)


    # Initial values
    D1 = W * DOC * DOCf * MCF
    B[1] = D1 * exp2
    C[1] = D1 * (1 - exp2)
    H[0] = 0
    Q[1] = E[1] * 16 / 12 * F

    n = 101 #assuming 100 years of methane emissions

    # Perform calculations
    for i in range(1, n):
        D = 0  # Set D to 0 for all iterations except the first
        if i == 1:
            D = D1  # Set D to D1 for the first iteration
        B[i] = D * exp2
        C[i] = D * (1 - exp2)
        H[i] = B[i] + H[i - 1] * exp1
        E[i] = C[i] + H[i - 1] * (1 - exp1)
        Q[i] = E[i] * 16 / 12 * F

    # Calculate total CH4
    Total_CH4 = sum(Q[1:])
    print("Total CH4 emissions:", Total_CH4)

    # Update input_data DataFrame with Total_CH4 value
    input_data.at[index, "Total_CH4"] = Total_CH4


# Specify the path for saving the output within Colab
output_path_colab = "/content/output.xlsx"
input_data.to_excel(output_path_colab, index=False)

# Provide a link to download the file
from google.colab import files
files.download(output_path_colab)



print("Output Excel file generated:", output_path_colab)